CREATE TABLE `ORDERS`
(
`ID` BIGINT NOT NULL,
`CONVERSE_ID` BIGINT,
`PAIR` VARCHAR(50) NOT NULL,
`OPERATION` VARCHAR(50) NOT NULL,
`AMOUNT` DOUBLE NOT NULL,
`PRICE` DOUBLE NOT NULL,
`CONVERSE_PRICE`DOUBLE,
`CREATE_DATE` DATETIME,
`DONE_DATE` DATETIME,
`CLOSE_DATE` DATETIME,
`CLOSED` BOOL NOT NULL,
`SPREAD` DOUBLE,
`PROFIT` DOUBLE,
CONSTRAINT `PK_ORDERS` PRIMARY KEY (`ID`)
);