CREATE TABLE `ORDERS`
(
`ID` BIGINT NOT NULL,
`PAIR` VARCHAR(50) NOT NULL,
`OPERATION` VARCHAR(50) NOT NULL,
`AMOUNT` DOUBLE NOT NULL,
`PRICE` DOUBLE NOT NULL,
`PENDING` DOUBLE NOT NULL,
`CREATE_DATE` DATE,
`CLOSE_DATE` DATE,
`RELEASE_DATE` DATE,
`RELEASED` BOOL NOT NULL,
`PROFIT` DOUBLE, CONSTRAINT
`PK_ORDERS` PRIMARY KEY (`ID`)
);