CREATE TABLE grid
(
id BIGINT NOT NULL,
pair VARCHAR(50) NOT NULL,
operation VARCHAR(50) NOT NULL,
amount FLOAT NOT NULL,
price DECIMAL NOT NULL,
create_date DATE,
CONSTRAINT pk_grid PRIMARY KEY (id)
);

CREATE SEQUENCE grid_id_seq;