CREATE TABLE GRID
(
ID BIGINT NOT NULL,
PAIR VARCHAR(50) NOT NULL,
OPERATION VARCHAR(50) NOT NULL,
AMOUNT FLOAT NOT NULL,
PRICE DECIMAL NOT NULL,
CREATE_DATE DATE,
CONSTRAINT PK_GRID PRIMARY KEY (ID)
);

CREATE SEQUENCE grid_id_seq;